### ISSUE TITLE
Table sorting hides all rows in 2.4.16

### ISSUE THREAD

**Issue by avdempsey** [colinaut/action-table#14]
Updating from 2.4.15 to 2.4.16 breaks sorting. As soon as a header is clicked all rows disappear. Clicking other headers doesn't change anything.

I see the same behavior in tables small and large. There are no console errors. Tested in desktop Chrome and Safari.

Reverting to 2.4.15 fixes the issue.

```html
<html lang="en">
<head>
  <title>Action</title>
  <script type="module" src="/static/neighborhood/bundle.js"></script>
  <link rel="stylesheet" href="/static/neighborhood/action-table/action-table.css" />
</head>
<body>
  <action-table>
    <table>
      <thead>
        <tr>
          <th>A</th>
          <th>B</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>2</td>
          <td>4</td>
        </tr>
        <tr>
          <td>1</td>
          <td>5</td>
        </tr>
      </tbody>
    </table>
  </action-table>
</body>
</html>
```

**Comment by colinaut** [comment]
Ah thanks. Found the bug. I failed to initialize the set I used for knowing which rows to filter, resulted in empty rows.

Fixed in [2.4.17](https://github.com/colinaut/action-table/releases/tag/2.4.17)

**Comment by avdempsey** [comment]
Awesome, that fixed it.

Thank you so much for this great library. It's helping my team keep track of infrastructure at the Internet Archive.

**Comment by colinaut** [comment]
Oh that's awesome! I'm glad it's useful for your team. The Internet Archive is great.
