### ISSUE TITLE
Change filter-text

### ISSUE THREAD

**Issue by eydun** [colinaut/action-table#2]
Thank you for building this awesome component!

Would it be possible to manually set the "All"-text in the filter to something else?

**Comment by colinaut** [comment]
Good idea! I'm working on some other changes so I'll pull this into the next release which should be ready today or tomorrow.

**Comment by colinaut** [comment]
Ok as of release 2.4.1 I added an `all` attribute to `<action-table-filter-menu>` so you can supply your own text for "All"
