### ISSUE TITLE
Provide a method for localising strings

### ISSUE THREAD

**Issue by paulrobertlloyd** [colinaut/action-table#4]
There are a number of strings currently hard-coded into the component. This means it’s not possible to either change their value, or provide localised alternatives.

Of note, I’ve found the following hard-coded strings:

* ‘Reset’
* ‘No Results’
* ‘Reset Filters’
* ‘Pagination’

**Comment by colinaut** [comment]
Good idea to make this changeable. I'll work on adding the ability to change this. I'll add it to my next release which should come out today or tomorrow.

**Comment by colinaut** [comment]
Ok as of the most recent release 2.4.1, these are all modifiable.

The no results area is now it's own custom element `<action-table-no-results>` which you can write whatever you want, style however, and locate where ever. It handles hiding/showing and creating a click event for any reset button.

**Example Usage**

```
<action-table-no-results>
	<strong><em>No results found</em></strong> <button type="reset">Reset Filters</button>
</action-table-no-results>
```

`<action-table-pagination>` now has a new label attribute. As pagination now shows current rows and total rows. This attribute is special as it automatically string replaces {rows} for the current rows range and {total} for the total rows. _Defaults to "Showing {rows} of {total}:"_

There is also a new `<action-table-pagination-options>` element id you want to a select menu that allows users to choose the number of rows per page.

**Comment by paulrobertlloyd** [comment]
Amazing, thank-you so much for quickly addressing this issue!
