### ISSUE TITLE
feature request: reverse order of items in filter drop down

### ISSUE THREAD

**Issue by benishs** [colinaut/action-table#5]
I have a dataset where one of the columns is a year. I have this column configured to be one of the options for filtering.

By default the items in that filter drop down are sorted ascending (1921, 1922, 1923, _etc. all the way to 2022_), as you'd expect: https://go.benish.io/WQftwl7p

But I think most viewers will be interested in the more recent years, so I'd like to reverse the order that items appear in that drop down: 2022, 2021, _etc._ 

I'm picturing something like:
`<action-table-filter-menu name="Year" order="descending"></action-table-filter-menu>`
where if the `order` attribute is omitted it defaults to ascending (the current behavior).

**Comment by benishs** [comment]
Possibly related feature request: https://github.com/colinaut/action-table/issues/6

**Comment by colinaut** [comment]
Solid idea. Should be easy to implement. I'll add it to the list. I probably will have time this week for it.

**Comment by colinaut** [comment]
Added to latest release 2.4.2. Just add descending attribute like so:
```
<action-table-filter-menu name="Year" descending></action-table-filter-menu>
```

**Comment by benishs** [comment]
🙌 Thank you!
