### ISSUE TITLE
Editable column item gets deselected upon change.

### ISSUE THREAD

**Issue by EclipseKnight** [colinaut/action-table#9]
Hi, 

I'd like to preface this by saying thank you for this amazing and simple to use web component! It has saved me a lot of time in redesigning existing tables to implement simple filter functions and searches. So I'm very grateful!

I have run into a particular issue, and this may be in part to how I implemented it. 
Essentially, I have a column in a table that allows you to double-click on a cell and change the value. It modifies the innerHTML to be specific.

It seems when trying to type the new value, it takes 1 character and then deselects the cell and reapplies filtering rules immediately. You then have to double-click on the same cell and finish typing the additional characters. This was working before wrapping the table with the action-table template.

For example: here is the table in question and the cell is currently selected and the value is highlighted following a double-click. 
![image](https://github.com/colinaut/action-table/assets/32472185/3096e8cd-d9f4-438e-a570-378c730513fc)

It seems there may be a relation with the attributeChangeCallback that could be causing the issue. 
In the example picture, if I were to clear "10" it would deselect and leave the cell empty. From an empty cell, if I double-click and type any one number or character, it deselects the cell and sets the value to that one number or character.
![image](https://github.com/colinaut/action-table/assets/32472185/262b3d94-7ada-4605-980b-0b5aaf794dc0)

The only times it doesn't deselect are if you start making changes to the value by adding additional characters or removing all but 1 character. 

I apologize for the long-winded explanation, please let me know if you'd like me to get additional information!

**Comment by colinaut** [comment]
Interesting edge case. There might be a way to augment it either with a functionality enhancement on my end or on your script that is updating the cell innerText. To explain that let me explain how the action-table and it's mutation observer currently works:

1.  On initialization, Action Table scans the entire table and stores the textContent as a special actionTable variable property on the td DOM element. The reason it does this as it's much more efficient to sort and filter off of a variable than reading textContent every time.
2. When the text of a cell changes, the mutation observer updates td.actionTable and calls sortAndFilter()
3. sortAndFilter() has a "wait for more changes" delay of 10ms which is fast enough that no human would notice the delay but slow enough for situations where you have cells that update on load. _For example, see my random number custom element in the example table's Age column._ 10ms however is way too fast for typical typing speed. So in your example, every letter you type triggers sortAndFilter().

I have a couple ideas how to fix this on my end:

1. Add an attribute on action-table so you can set your own delay speed for sortAndFilter. This is easy but also has other side effects like it would delay.
2. Add some function to the mutation observer which somehow recognizes that a cell is being currently updated. I'm not exactly sure how to handle this. _Maybe tie maybe tie into detecting a contenteditable change somehow?_

You could also change the code on your end. I'm not sure how you are handling it currently. If you are using contenteditable, I haven't tested this but it's likely detecting the change every letter typed and triggering sortAndFilter(). If you are instead doing something else like adding an input with an eventListener to update the innerText with javascript then you could either: 

1. switch to a blur event which only updates the cell when they tab out of the input
2. add a debounce which delays updating the cell until they stop typing

Anyways, that's a long winded reply. I may have time to look into making changes on my end but I'm rather busy right now so no promises. However, if it's an easy change on your end then great!

**Comment by colinaut** [comment]
Just tested contenteditable and apparently mutationobserver is not triggered when content is changed in a contenteditable cell? That's interesting. I'm curious to look into why that is.

Anyways @EclipseKnight now I know you are likely using some sort of javascript added input with an eventListener. You can then likely use blur or a debounce to delay updating the cell's content which will fix your issue.

**Comment by EclipseKnight** [comment]
Yes you are correct! I am using contenteditable cell and have an eventListener and some javascript to handle it all. 

You're reproduction of the issue sounds similar. When content is cleared it deselects and when content is initially added it deselects. If I were to manipulate the existing content there are no issues until that last character is cleared. Writing this out it does sound identical to what you were able to reproduce. 

I'll try to use blue/debounce and report of it resolves!

**Comment by EclipseKnight** [comment]
I was quickly able to test blur with no luck. The issue persisted. With how it is currently coded, the content is only updated upon clicking out of the cell or via the enter or escape key so I don't believe adding a delay would change anything unless I'm misunderstanding. I apologize, I mainly do backend so my frontend experience is limited.

**Comment by colinaut** [comment]
OK yeah in my limited test, contenteditable triggers in strange ways with mutation observer. I might be able to sort out a way to do it inside the action table mutation observer function. I'll take another look at it today and let you know if it's something I can do or something that needs to be put off until I have more time.

**Comment by EclipseKnight** [comment]
Sounds good! Thank you again!

**Comment by colinaut** [comment]
Ok so I have a dev version that works for this! It incorporates wait till blur on contenteditable cells into the mutation observer function. I need to QA it some more and clean up the code, but I should be able to push a new release with this soon. Probably sometime this weekend.

**Comment by EclipseKnight** [comment]
That's great! Thank you so much for taking the time to fix this weird edge case lol

**Comment by colinaut** [comment]
I had some time and it was an interesting problem so I got it done. New release [2.4.14](https://github.com/colinaut/action-table/releases/tag/2.4.14) includes working contenteditable fix so it updates on blur automatically. All you need to do is add contenteditable to the td and it will work.

I'm gonna close this comment but full free to reply if you have problems, as I can reopen it if need be.
